--SQLQuery0-CREATE DATABASE.sql


CREATE DATABASE PV_521_DDL
ON
(
NAME = PV_521_DDL,
FILENAME = 'D:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\PV_521_DML.mdf',
SIZE = 8 MB,
MAXSIZE = 500 MB,
FILEGROWTH = 8 MB
)

LOG ON
(
NAME = PV_521_DDL_log,
FILENAME = 'D:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\PV_521_DML.ldf',
SIZE = 8 MB,
MAXSIZE = 500 MB,
FILEGROWTH = 8 MB
)